name: api_service_example
description: An example project demonstrating the use of the api_service package.
version: 1.0.0

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  http_api_service: ^1.0.3

dev_dependencies:
  lints: ^2.0.0 # Optional, for linting your example code
