name: http_api_service
description: A simple and reusable HTTP service for Flutter applications.
version: 1.0.0
homepage: https://github.com/naneps/api_service
repository: https://github.com/naneps/api_service


environment:
  sdk: ^3.6.0
  flutter: ">=1.17.0"

dependencies:
  http: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

